version: '3.4'

services:
  dockerimage:
    image: dockerimage:setup
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8888:8888
      - 8787:8787
      - 8686:8686
      - 5000:5000