name: ml-env
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - anaconda
  # - bioconda
dependencies:
  - black
  - catboost
  - cudatoolkit
  - cuml
  - dask-cudf
  - dask=2022.6.1
  - dask-cuda
  - flask
  - fugue
  - fugue
  - ipykernel
  - joblib
  - jupyterlab_widgets
  - mlflow
  # - nb_conda_kernels
  - numba=0.56.4
  - numpy=1.22
  - pandas
  - pip
  - pynvml
  - python=3.8
  - rmm
  - scikit-learn=1.1.3
  - scipy=1.8.1 
  - swifter
  - xgboost
  # added after last build -> not tested
  # - scikit-learn-intelex  # has issue caused by daal
  - sktime>=0.14.0
  - pip:
      - setuptools
      # - pycaret[full]==3.0.0rc5
      - git+https://github.com/pycaret/pycaret.git@master