name: ml-env
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - anaconda
  # - bioconda
dependencies:
  - python=3.8
  - pip
  - cudatoolkit
  - pandas
  - cuml
  - swifter
  - numpy=1.22
  - numba=0.56.4
  - joblib
  - dask=2022.6.1
  - black
  - flask
  - nb_conda_kernels
  # added after last build -> not tested
  - mlflow
  - scikit-learn=1.1.3
  - scipy=1.8.1 
  - pynvml
  - pip:
      - pycaret==3.0.0rc4